const ActionTypes={
    REST_LOADING:"REST_LOADING",
    REST_SUCCES:"REST_SUCCES",
    REST_ERROR:"REST_ERROR",

    CART_LOADING:"CART_LOADING",
    CART_SUCCES:"CART_SUCCES",
    CART_ERROR:"CART_ERROR",
    CREATE_ITEM:"CREATE_ITEM",
    UPDATE_ITEM:"UPDATE_ITEM",
    DELETE_ITEM:"DELETE_ITEM",
}
export default ActionTypes